# Generated by Django 2.0.5 on 2018-05-11 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightmanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='land_airport',
            new_name='arrival_airport',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='land_date',
            new_name='arrival_date',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='start_airport',
            new_name='departure_airport',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='start_date',
            new_name='departure_date',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='passanger',
            new_name='passenger',
        ),
        migrations.AlterField(
            model_name='airplane',
            name='seat_number',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(615), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='luggage_weight',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(0)]),
        ),
    ]
